In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('preprocessed_data.csv')

In [3]:
df.isnull().sum()

Unnamed: 0       0
sms              3
spam/ham_spam    0
dtype: int64

In [4]:
df.dropna(inplace=True)

In [5]:
df.head()

Unnamed: 0                                                sms  \
0           0  go until jurong point crazi avail onli in bugi...   
1           1                              ok lar joke wif u oni   
2           2  free entri in a wkli comp to win fa cup final ...   
3           3        u dun say so earli hor u c alreadi then say   
4           4  nah i don t think he goe to usf he live around...   

   spam/ham_spam  
0              0  
1              0  
2              1  
3              0  
4              0

In [6]:
df.reset_index()

index  Unnamed: 0                                                sms  \
0         0           0  go until jurong point crazi avail onli in bugi...   
1         1           1                              ok lar joke wif u oni   
2         2           2  free entri in a wkli comp to win fa cup final ...   
3         3           3        u dun say so earli hor u c alreadi then say   
4         4           4  nah i don t think he goe to usf he live around...   
...     ...         ...                                                ...   
5161   5164        5164  thi is the nd time we have tri contact u u hav...   
5162   5165        5165                      will b go to esplanad fr home   
5163   5166        5166      piti wa in mood for that so ani other suggest   
5164   5167        5167  the guy did some bitch but i act like i d be i...   
5165   5168        5168                            rofl it true to it name   

      spam/ham_spam  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0  
...             ...  
5161              1  
5162              0  
5163              0  
5164              0  
5165              0  

[5166 rows x 4 columns]

In [7]:
df.duplicated().sum()

0

In [8]:
df['spam/ham_spam'].value_counts()

spam/ham_spam
0    4513
1     653
Name: count, dtype: int64

In [9]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
cv= CountVectorizer(max_features=3000, stop_words='english')
tfidf= TfidfVectorizer(max_features=3000)

In [10]:
X_cv = cv.fit_transform(df['sms']).toarray()

In [11]:
X_tfidf = tfidf.fit_transform(df['sms']).toarray()

In [12]:
y=df['spam/ham_spam'].values

In [13]:
#TFIDF

In [14]:
from sklearn.model_selection import train_test_split
X_tf_train, X_tf_test, y_tf_train, y_tf_test= train_test_split(X_tfidf, y, test_size=0.3, random_state=42)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB, GaussianNB, MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [16]:
rf= RandomForestClassifier()
svm= SVC()
mnb= MultinomialNB()
gnb= GaussianNB()
bnb= BernoulliNB()

In [17]:
mnb.fit(X_tf_train, y_tf_train)
y_prid_mnb = mnb.predict(X_tf_test)
print(accuracy_score(y_tf_test, y_prid_mnb))
print(precision_score(y_tf_test, y_prid_mnb))
print(confusion_matrix(y_tf_test,y_prid_mnb))

0.9722580645161291
1.0
[[1344    0]
 [  43  163]]


In [18]:
gnb.fit(X_tf_train, y_tf_train)
y_prid_gnb = gnb.predict(X_tf_test)
print(accuracy_score(y_tf_test, y_prid_gnb))
print(precision_score(y_tf_test, y_prid_gnb))
print(confusion_matrix(y_tf_test,y_prid_gnb))

0.8812903225806452
0.534375
[[1195  149]
 [  35  171]]


In [19]:
bnb.fit(X_tf_train, y_tf_train)
y_prid_bnb = bnb.predict(X_tf_test)
print(accuracy_score(y_tf_test, y_prid_bnb))
print(precision_score(y_tf_test, y_prid_bnb))
print(confusion_matrix(y_tf_test,y_prid_bnb))

0.9864516129032258
0.9792746113989638
[[1340    4]
 [  17  189]]


In [20]:
rf.fit(X_tf_train,y_tf_train)
y_pred_rf = rf.predict(X_tf_test)
print(accuracy_score(y_tf_test, y_pred_rf))
print(precision_score(y_tf_test, y_pred_rf))
print(confusion_matrix(y_tf_test,y_pred_rf))

0.9774193548387097
0.9885714285714285
[[1342    2]
 [  33  173]]


In [21]:
svm.fit(X_tf_train,y_tf_train)
y_pred_svm = svm.predict(X_tf_test)
print(accuracy_score(y_tf_test, y_pred_svm))
print(precision_score(y_tf_test, y_pred_svm))
print(confusion_matrix(y_tf_test,y_pred_svm))

0.9793548387096774
0.9887640449438202
[[1342    2]
 [  30  176]]


In [170]:
#BOG

In [171]:
from sklearn.model_selection import train_test_split
X_bow_train, X_bow_test, y_bow_train, y_bow_test= train_test_split(X_cv, y, test_size=0.3, random_state=42)

In [172]:
mnb.fit(X_bow_train, y_bow_train)
y_prid_mnb_bow = mnb.predict(X_bow_test)
print(accuracy_score(y_bow_test, y_prid_mnb_bow))
print(precision_score(y_bow_test, y_prid_mnb_bow))
print(confusion_matrix(y_bow_test,y_prid_mnb_bow))

0.9819354838709677
0.9045454545454545
[[1323   21]
 [   7  199]]


In [173]:
gnb.fit(X_bow_train, y_bow_train)
y_prid_gnb_bow = gnb.predict(X_bow_test)
print(accuracy_score(y_bow_test, y_prid_gnb_bow))
print(precision_score(y_bow_test, y_prid_gnb_bow))
print(confusion_matrix(y_bow_test,y_prid_gnb_bow))

0.8722580645161291
0.5115606936416185
[[1175  169]
 [  29  177]]


In [174]:
bnb.fit(X_bow_train, y_bow_train)
y_prid_bnb_bow = bnb.predict(X_bow_test)
print(accuracy_score(y_bow_test, y_prid_bnb_bow))
print(precision_score(y_bow_test, y_prid_bnb_bow))
print(confusion_matrix(y_bow_test,y_prid_bnb_bow))

0.983225806451613
0.9787234042553191
[[1340    4]
 [  22  184]]


In [175]:
rf.fit(X_bow_train,y_bow_train)
y_pred_bow_rf = rf.predict(X_bow_test)
print(accuracy_score(y_bow_test, y_pred_bow_rf))
print(precision_score(y_bow_test, y_pred_bow_rf))
print(confusion_matrix(y_bow_test,y_pred_bow_rf))

0.9774193548387097
1.0
[[1344    0]
 [  35  171]]


In [176]:
svm.fit(X_bow_train,y_bow_train)
y_pred_bow_svm = svm.predict(X_bow_test)
print(accuracy_score(y_bow_test, y_pred_bow_svm))
print(precision_score(y_bow_test, y_pred_bow_svm))
print(confusion_matrix(y_bow_test,y_pred_bow_svm))

0.9793548387096774
1.0
[[1344    0]
 [  32  174]]


In [177]:
df={
    "Models":[],
    "accuracy_score":[],
    "precision_score":[]
}

In [178]:
#TFIDF df
model=['mnb', 'bnb', 'gnb', 'rf', 'svm']
def performace(x, y):
    models=[mnb, bnb, gnb, rf, svm]
    X_train, X_test, y_train, y_test= train_test_split(x, y, test_size=0.3, random_state=42)
    
    for i in range(len(models)):
        models[i].fit(X_train, y_train)
        y_pred = models[i].predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        df["Models"].append(model[i])
        df["accuracy_score"].append(accuracy)
        df["precision_score"].append(precision)
    return df

In [179]:
data = performace(X_tfidf, y)

In [180]:
data

{'Models': ['mnb', 'bnb', 'gnb', 'rf', 'svm'],
 'accuracy_score': [0.9722580645161291,
  0.9864516129032258,
  0.8812903225806452,
  0.9761290322580645,
  0.9793548387096774],
 'precision_score': [1.0,
  0.9792746113989638,
  0.534375,
  0.9884393063583815,
  0.9887640449438202]}

In [181]:
pd.DataFrame(data)

Models  accuracy_score  precision_score
0    mnb        0.972258         1.000000
1    bnb        0.986452         0.979275
2    gnb        0.881290         0.534375
3     rf        0.976129         0.988439
4    svm        0.979355         0.988764

In [182]:
import pickle

In [185]:
pickle.dump(tfidf,open('vectorizer.pkl','wb'))

In [186]:
pickle.dump(mnb, open('model.pkl','wb'))